goal: MINIMIZE
maxTrials: 50
maxParallelTrials: 10
hyperparameterMetricTag: ai4ops_lightgbm_mae_tag
enableTrialEarlyStopping: TRUE
params:
- parameterName: colsample_bytree
  type: DOUBLE
  minValue: 0.001
  maxValue: 1.000
- parameterName: learning_rate
  type: DOUBLE
  minValue: 0.0001
  maxValue: 1.0
- parameterName: max_depth
  type: INTEGER
  minValue: 5
  maxValue: 100
- parameterName: min_child_samples
  type: INTEGER
  minValue: 1
  maxValue: 200
- parameterName: min_child_weight
  type: DOUBLE
  minValue: 0.001
  maxValue: 100.00
- parameterName: min_split_gain
  type: DOUBLE
  minValue: 0.0
  maxValue: 1.0
- parameterName: n_estimators
  type: INTEGER
  minValue: 50
  maxValue: 700
- parameterName: num_leaves
  type: INTEGER
  minValue: 100
  maxValue: 1000
- parameterName: reg_alpha
  type: DOUBLE
  minValue: 0.0
  maxValue: 100.0
- parameterName: reg_lambda
  type: DOUBLE
  minValue: 0.0
  maxValue: 100.0
- parameterName: subsample
  type: DOUBLE
  minValue: 0.001
  maxValue: 1.000
- parameterName: subsample_freq
  type: INTEGER
  minValue: 0
  maxValue: 100
